farhad85/MasteringGit

Lists/Students/1504166/cities.txt
Lists/Students/cities.txt
answers.txt

Hi,
I am the seventh student who made change in student list file.

Adding branch 1504166

---

Lists/Students/1708500/cities.txt
answers.txt

Added favorite cities. Also added answers to answers.txt.

Kasperi Klaavo favorite cities

---

Lists/Students/1602068/cities.txt
answers.txt

Added cities and edited answers.txt

---

Lists/Students/1605342/cities.txt

Thien Ly : My favorite cities

---

Lists/Students/1305923/cities.txt
answers.txt

pull request created

---

Lists/Students/1800101/cities.txt
answers.txt

This reverts commit f516775b140a1edd15e2110f6afe46e17c42b09d.

Revert "Tudor Nica: My favorite cities"

---

Lists/Students/1708593/cities.txt
answers.txt

Pull request regarding the course project, step 12.

Step 12 pull request

---

Lists/Students/saraalka/cities.txt

This is the pull request, required to complete the course project

saraalka: My favorite cities

---

Lists/Students/1808804/cities.txt
answers.txt

I have done Course-project. Please check that I did correctly.

harivisa: My favorite cities

---

Lists/Students/syloas/cities.txt
answers.txt

Pull request for modified files. Created cities.txt and modified answers.txt.

Simone Ylönen: My favorite cities

---

Lists/Students/GIT001/cities.txt
answers.txt

Salvador Dukuzumuremyi: My favorite cities

---

answers.txt

Sami Pekkala: My favorite cities

Sami's changes

---

answers.txt

Changes done as instructed in Final Tasks: Course Project

PULL request for GIT course

---

Lists/Students/2016365/cities.txt
answers.txt

Added file Lists/Students/2016365/cities.txt
Edited file answers.txt

My contribution to course project

---

Lists/Students/2102990/cities.txt

Course project exercise for pull request

2102990: My favourite cities

---

Lists/Students/2018746/cities.txt
answers.txt

@farhad85  Check this out for review.

Arnel Imperial: My favorite cities

---

answers.txt

Estudent 2018746

---

answers.txt

Added citities.txt for 10101010 and modified answers.txt

Added citities.txt for 10101010 and modified answers.txt

---

answers.txt

This jibril with student id 2107105

JIBRIL FAVORITE CITIES

---

Lists/Students/JuliaMur/cities.txt
answers.txt

Julia Koshevaia: My favorite cities

---

Lists/Students/soundharya/cities.txt
answers.txt

MasteringGit Final Project - Pull Request Testing

{soundharya}:My favorite cities

---

Lists/Students/ranjithajois/cities.txt
answers.txt

ranjithaJois: My favorite cities

---

Lists/Students/2217515/cities.txt
answers.txt

Tero anttila
